### ISSUE TITLE
Call to deprecated function recognize_song. Use recognize method instead of recognize_song

### ISSUE THREAD

**Issue by grvulture** [davidAlgis/mp3ShazamAutoTag#4]
I'm getting this:
"DeprecationWarning: Call to deprecated function recognize_song. Use recognize method instead of recognize_song"
which is coming from Shazam.

I fixed it on my installation by renaming the function call, no big deal, but I thought I'd let you know...
Kudos on this, works like a charm!!

**Comment by davidAlgis** [comment]
Thanks for your message !
I didn't notify this warning, because I had an older version of `shazamio` module. I update it to remove the warning as you suggest.
